### ISSUE TITLE
Not working in IE 8 

### ISSUE THREAD

**Issue by nileshku** [nbartlomiej/foggy#4]

**Comment by nbartlomiej** [comment]
Thanks for the feedback! Please provide more details. A screenshot and the source code of the page that doesn't work would be most helpful.

**Comment by nileshku** [comment]
I was checking the plugin demo in IE8 mode. Please find attached screenshot .
btw really nice plugin
![foggy-notworking](https://f.cloud.github.com/assets/3539629/594624/89eeb768-ca9f-11e2-9ada-f7c27637fd7d.png)

**Comment by nbartlomiej** [comment]
Thanks for the details! Will try to investigate this soon.

**Comment by calvinte** [comment]
I'm experiencing this as well.

**Comment by nbartlomiej** [comment]
Fixed by @watsoncj in [his PR](https://github.com/nbartlomiej/foggy/pull/7). Big thanks!

Funny thing is, the bug wasn't present in the minified file; there's no difference between jquery.foggy.min.js version 1.1 and version 1.1.1 (apart from randomized variable names). [The fix](https://github.com/nbartlomiej/foggy/commit/fb7e91a4f21ec31a99717384bf0976e8dafc57e9#diff-f2caa97514a1e90baf3214300da3ec78R39) was all about using different literal notation, and it turns out that the minifier converted everything to that notation anyway.

Summarizing:

1) If you were using jquery.foggy.**min**.js v1.1, there's no need for you to update.
2) If you were playing with jquery.foggy.js v1.1, please do update, switch to jquery.foggy.js v1.1.1 .
